apiVersion: v1
kind: Service
metadata:
  name: flappy-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flappy-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
