apiVersion: v1
kind: Service
metadata:
  name: {{ include "flappybird.fullname" . }}-backend
  namespace: {{ include "flappybird.namespace" . }}
  labels:
    {{- include "flappybird.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP

