{{- if .Values.backend.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.name }}
  namespace: {{ include "flappybird.namespace" . }}
  labels:
    {{- include "flappybird.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASS: "{{ .Values.backend.secret.dbPassword }}"
{{- end }}

