{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flappybird.fullname" . }}-ingress
  namespace: {{ include "flappybird.namespace" . }}
  labels:
    {{- include "flappybird.labels" . | nindent 4 }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml .Values.frontend.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "flappybird.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "flappybird.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
    {{- end }}
{{- end }}

