apiVersion: v1
kind: Service
metadata:
  name: {{ include "flappybird.fullname" . }}-frontend
  namespace: {{ include "flappybird.namespace" . }}
  labels:
    {{- include "flappybird.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP

