{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flappybird.fullname" . }}-grafana
  namespace: {{ include "flappybird.namespace" . }}
  labels:
    {{- include "flappybird.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
{{- end }}

