apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flappybird
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Techikrish/Flappybird-DevSecOps
    targetRevision: main
    path: helm/flappybird
    helm:
      releaseName: flappybird
      values: |
        global:
          namespace: flappybird
  destination:
    server: https://kubernetes.default.svc
    namespace: flappybird
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

