apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappy-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flappy-frontend
  template:
    metadata:
      labels:
        app: flappy-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_URL
              value: {{ .Values.env.backendUrl }}
