apiVersion: v1
kind: Service
metadata:
  name: flappy-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flappy-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
