global:
  namespace: flappybird
  imagePullSecrets: []

backend:
  replicaCount: 2
  image:
    repository: docker.io/USERNAME/flappybird-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  env:
    dbHost: ""
    dbPort: "5432"
    dbName: "flappydb"
    dbUser: "flappy"
    dbSslMode: "require"
  secret:
    create: true
    name: flappybird-backend-db
    dbPassword: ""
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  replicaCount: 2
  image:
    repository: docker.io/USERNAME/flappybird-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: flappybird.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

