replicaCount: 1

image:
  repository: YOUR_DOCKERHUB_USERNAME/flappy-frontend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

env:
  backendUrl: "http://backend.flappy.local"

ingress:
  enabled: true
  className: nginx
  host: "flappy.local"
